import { Brand } from "../components/brand";

const content = {
  privacy: { title: "Privacy", updated: "July 18, 2026", sections: [["What IntentHour collects", "Free sessions remain in your browser for seven days. Pro accounts store your email, completed sessions, outcomes, interruption categories, and billing entitlement in our cloud database."], ["What we never collect", "IntentHour does not monitor your screen, applications, browser history, keystrokes, or clipboard."], ["AI weekly reviews", "AI reviews require explicit consent. Only aggregate durations, outcome labels, time buckets, and interruption counts are sent to OpenAI. Your email, intention text, and free-form notes are excluded."], ["Payments", "Paddle processes payments and maintains the financial records required for tax and legal compliance. IntentHour receives transaction identifiers and entitlement status."], ["Your choices", "You can disable AI reviews, export Pro data, or delete your IntentHour account data from Settings."]] },
  terms: { title: "Terms", updated: "July 18, 2026", sections: [["The service", "IntentHour is a focus-session and reflection tool. It does not promise a particular productivity, employment, health, or financial outcome."], ["Pro Lifetime", "A $39 Pro Lifetime purchase grants continued access to IntentHour v1.x features for as long as that version is operated. Future major versions may be offered separately."], ["Acceptable use", "Do not abuse, reverse engineer, overload, or use the service to violate law or another person's rights."], ["Availability", "We work to keep the service reliable, but maintenance, provider incidents, and product changes may cause interruptions."], ["Contact", "Questions about these terms can be sent through the Contact page."]] },
  refund: { title: "Refund policy", updated: "July 18, 2026", sections: [["Requesting a refund", "Contact us with the email used at checkout and your transaction reference. Refunds are handled through Paddle and may require Paddle approval."], ["Access after a refund", "When a full refund is approved or a chargeback succeeds, Pro access is revoked. Partial adjustments are reviewed manually."], ["Data", "A refund does not automatically delete your focus data. You can delete account data separately from Settings."]] },
} as const;

export function LegalPage({ kind }: { kind: keyof typeof content }) { const page = content[kind]; return <div className="legal-page"><header><Brand /><a href="/">Back to product</a></header><main><h1>{page.title}</h1><p>Last updated {page.updated}</p>{page.sections.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}</main></div>; }
export function ContactPage() { return <div className="legal-page"><header><Brand /><a href="/">Back to product</a></header><main><h1>Contact</h1><p>Questions about IntentHour, privacy, accessibility, or a Paddle purchase?</p><section><h2>Email</h2><p><a href="mailto:hello@intenthour.com">hello@intenthour.com</a></p><p>Include the checkout email and Paddle transaction reference for billing requests. Never send passwords or API keys.</p></section><section><h2>Response time</h2><p>We aim to reply within two business days.</p></section></main></div>; }
